name: Deploy Fnt

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/financial-news-tracker

            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Stopping old containers..."
            docker-compose down || true

            echo "Rebuilding and starting containers..."
            docker-compose up -d --build

            echo "Cleaning up unused Docker images..."
            docker system prune -af
